// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmNuuUUoZ8wxsWHV1intjan5Uj1WFLznE',
    appId: '1:605253573366:android:28c5b1220738a626962ad7',
    messagingSenderId: '605253573366',
    projectId: 'primeiro-app-flutter-3e043',
    storageBucket: 'primeiro-app-flutter-3e043.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_8SUWkzOTMPwcpr_WM38z5p-jzTPB2OI',
    appId: '1:605253573366:ios:83c875b2586b807d962ad7',
    messagingSenderId: '605253573366',
    projectId: 'primeiro-app-flutter-3e043',
    storageBucket: 'primeiro-app-flutter-3e043.firebasestorage.app',
    iosBundleId: 'br.com.alexwilliam.primeiroapp.primeiroAppFluuter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfxkGMRhjE5lGdecinvHO3nn3iQXsShxE',
    appId: '1:605253573366:web:1cb5973e87d7e3ea962ad7',
    messagingSenderId: '605253573366',
    projectId: 'primeiro-app-flutter-3e043',
    authDomain: 'primeiro-app-flutter-3e043.firebaseapp.com',
    storageBucket: 'primeiro-app-flutter-3e043.firebasestorage.app',
    measurementId: 'G-S9CSL4GNKK',
  );

}